/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:ac3710ce-3508-4a01-aa4c-0bc3a8a44d75",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_qtbQKA5bm",
    "aws_user_pools_web_client_id": "4ghf5pjm7cjm6uv82ajk1u2ubu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://scppcd5mljgrviazirah7kx6se.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qynz3k6xhzatzhyvg62qlxdnbu"
};


export default awsmobile;
